### PR TITLE
Create BoostCommand

### PR DESCRIPTION
**Pull request by ellzie**
Answers a very simple question

### CODE REVIEW

**Comment by lundylizard** [comment]
#36 changes the command system drastically, if emonky wants i can add this to the overhaul but it seems a little useless

**Review by lundylizard — CHANGES_REQUESTED** [review]
Refer to my comment.

**Comment by ellzie** [comment]
*answers most asked question in the server* "seems a little useless" but i understand if you REALLY dont want it

**Comment by lundylizard** [comment]
discord bot to incentivize individual level runs

**Comment by Em0nky** [comment]
It would be pretty close to the same amount of effort to use a bot command as just explaining to someone. I only implemented the command locally cause it was kind of a meme as is the text within the command. I don't really see it as necessary and don't really want to bloat the bot with excessive commands.

**Pull request closed without merging**
